version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: work-quest-client
    container_name: client
    ports:
      - 80:80
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_REST_API_URL=http://work-quest.com:4000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: work-quest-server
    container_name: server
    ports:
      - 4000:4000
