version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: dev-client
    container_name: dev-client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Tokyo

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: dev-server
    container_name: dev-server
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
    environment:
      TZ: Asia/Tokyo

  db:
    build: ./db
    image: dev-db
    container_name: dev-db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/sql
      - ./db/dump:/dump
    environment:
      MYSQL_DATABASE: work_quest
      MYSQL_USER: kenta
      MYSQL_PASSWORD: nre50678
      MYSQL_ROOT_PASSWORD: nre50678
      TZ: Asia/Tokyo
