version: "3"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/sql
    environment:
      MYSQL_DATABASE: work_quest
      MYSQL_USER: kenta
      MYSQL_PASSWORD: nre50678
      MYSQL_ROOT_PASSWORD: nre50678
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
