version: "3"
services:
  test_server:
    build:
      context: ./server
      dockerfile: "Dockerfile.test"
    container_name: test_server
    ports:
      - 4000:4000
    depends_on:
      - test_db
    command: >
      sh -c "./wait-for-it.sh -t 0 test_db:3306
      && npm test"
    environment:
      DB_HOST: test_db
      DB_USER: root
      DB_PASS: nre50678
      DB_PORT: 3306
      DB_DATABASE: test_db

  test_db:
    image: mysql:8.0.27
    container_name: test_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: nre50678
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
